
# this stage will fail if any tests fail or if test coverage is
# below the coverage specified in /coveralls.json

test:
  stage: security
  image: elixir:1.10.4-alpine

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix sobelow -i Config.HTTPS
